### ISSUE TITLE
values are repeated when ensuing statements return undef

### ISSUE THREAD

**Issue by tmcw** [tmcw/mistakes#3]
http://macwright.org/mistakes/#4718153

**Comment by tmcw** [comment]
The problem is that `eval('"hello world";\nvar x = 10;')` is 'hello world'. Not sure how we're going to fix this in jslandia.

**Comment by afeld** [comment]
Sounds like you want to split at newlines, no?

**Comment by tmcw** [comment]
Can't make that a hard and fast rule, unfortunately, since JS itself allows plenty of whitespace within expressions:

``` js
var x =


5;
console.log(x); // says 5
```

**Comment by afeld** [comment]
You can just split at semicolons, since _everyone_ uses those :-)

I suppose it might be possible to use an AST parser to get each statement individually.  A lot of work, probably.

**Comment by tmcw** [comment]
[esprima](http://esprima.org/) is the big axe for doing more advanced parsing - but it's a really big leap in complexity for this project, which is is currently <100 loc (not including dependencies like codemirror)

**Comment by afeld** [comment]
Yeah, totally understand.  Just to have them written down, [acorn](http://marijnhaverbeke.nl/acorn/) and [burrito](https://github.com/substack/node-burrito) seem like slightly lighter-weight options than esprima.

**Comment by tmcw** [comment]
Going to leave this as-is: better to be honest than clever.
