### ISSUE TITLE
es6?

### ISSUE THREAD

**Issue by kirbysayshi** [tmcw/mistakes#33]
I've been using mistakes as a bit of a live-coding environment, and one thing that would be really neat is to be able to use arrow functions and other es6 features. Have you given any thoughts to the challenges/possibility or transpiling to es6? It might be too slow to be practical.

**Comment by tmcw** [comment]
Hm - maybe, I don't know how robust transpilers are as far as giving useful line-exact parse errors, and reporting proper errors in the transpiled code. Without really strong error reporting, it'll be tricky to maintain the experience.

**Comment by tmcw** [comment]
Closing: while this is a great idea, thinking about mistakes2 it's going to have enough puzzles to solve without trying to do transpiling of any sort, whether it's es6/coffee/etc. So, happy to see other people implement this as PRs/forks, but it's not in my plans.
