### ISSUE TITLE
Auto-indent in editor

### ISSUE THREAD

**Issue by afeld** [tmcw/mistakes#6]
Looks like it's using Codemirror - should be easy to have it take care of this with the `smartIndent` option ([docs](http://codemirror.net/doc/manual.html)).

**Comment by tmcw** [comment]
I had this turned off explicitly for some reason. Turned it back on in 7f46ffb6d8f1d42a0c6abcbdd9e46deeb664e6c4 - it's pretty good, better than vim in some cases!
