### ISSUE TITLE
Show elements on right side

### ISSUE THREAD

**Issue by syntagmatic** [tmcw/mistakes#7]
If the line returns an element, that element should be appended to the div on the right.

For example, to create a data visualization, canvas art, or view an image/video.

**Comment by tmcw** [comment]
Heh, interesting idea. I'll look around for how tricky this is to do in CodeMirror, since it breaks a few assumptions (that output will be one line only and is the sole result of running code to a line #). Plus, don't want to step on @enjalot's tributary's toes too much

**Comment by enjalot** [comment]
you shouldn't worry about my toes ;)
but i do believe in the power of restrictive assumptions. you have a limited space to work in, but you can be efficient and effective within it.

this does remind me of another part of bret victor's talk where he shows the output of algorithms on the right. perhaps a mod of this wouldn't be restricted to one line on the right and behave something like docco?

**Comment by syntagmatic** [comment]
Even if the output's only the height of one line, I can think of at least a couple uses:
- Sparkline (to show the output of a function for a range, such as -2_pi to 2_pi on trig functions)
- Color palette viewer

But really I'm thinking about stages of a visualization, for teaching. Something like:
- View data plotted in rectilinear coordinates
- View graticules of geographic projection
- View data with projection applied
- Rotation and zoom of data on an interesting area
- List of dimensions in the dataset
- Styling data points by a measure
- Scatterplot comparing two measures

Right now bl.ocks and tributary aren't so convenient for showing these separate stages. They assume there's a single canvas and the end result is the important part.

**Comment by tmcw** [comment]
cool, if we can have these be either always a line or a line + 'expand' button I think it could work - just need to look around for a decent CodeMirror API for this.

**Comment by enjalot** [comment]
CodeMirror has markers and widgets, not sure which is best for this as I haven't delved as deep as I'd like to. would love to see what you come up with. I've been wanting to add console.log output inline to tributary for a while, which would need to behave similarly.

**Comment by tmcw** [comment]
I think I'm going to count this out of scope for mistakes - it's fertile ground for other projects, and this has been super productive brainstorming. The line-value metaphor doesn't work super well with non-text objects and DOM apis often don't have meaningful return values, so it would be a bit leaky conceptually.
